"""add_payments_and_void_fields

Revision ID: df343c9880fa
Revises: c2a753e64953
Create Date: 2026-08-19 02:30:57.366024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df343c9880fa'
down_revision: Union[str, Sequence[str], None] = 'c2a753e64953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_payments_id'), table_name='customer_payments')
    op.drop_table('customer_payments')
    op.add_column('sales', sa.Column('voided_at', sa.DateTime(), nullable=True))
    op.add_column('sales', sa.Column('void_reason', sa.Text(), nullable=True))
    op.add_column('sales', sa.Column('voided_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'users', ['voided_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'voided_by_user_id')
    op.drop_column('sales', 'void_reason')
    op.drop_column('sales', 'voided_at')
    op.create_table('customer_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('customer_payments_customer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('customer_payments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_payments_pkey'))
    )
    op.create_index(op.f('ix_customer_payments_id'), 'customer_payments', ['id'], unique=False)
    # ### end Alembic commands ###
